# Generated by Django 3.2 on 2021-04-07 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('I', 'In'), ('O', 'Out')], default=1, max_length=50, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='product',
            name='customer_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Customer Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='invoce_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Vendor Code'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Vendor Name'),
        ),
    ]
