# Generated by Django 3.2 on 2021-04-07 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210407_2106'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('vendor', 'model_no', 'serial_num')},
        ),
    ]
