# Generated by Django 3.2 on 2021-04-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_transfer_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='event_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Event Time'),
        ),
    ]
