# Generated by Django 3.2 on 2021-04-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_transfer_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Invoice Date'),
        ),
    ]
