# Generated by Django 3.2 on 2021-05-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210517_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('I', 'In'), ('O', 'Out'), ('S', 'Sold')], default='I', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterUniqueTogether(
            name='model',
            unique_together={('vendor', 'name')},
        ),
    ]
