# Generated by Django 3.2 on 2021-05-29 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='model',
            unique_together={('vendor', 'name')},
        ),
    ]
